### PR TITLE
fix: Return correct version iterating mem store in reverse

### LINKED ISSUE #22: Probable problem in mem.iterators.`loadLatestItem` returning wrong version of key-value
The loop:
```
for iter.it.Next() {
		if bytes.Equal(curItem.key, iter.it.Item().key) {
			curItem = iter.it.Item()
			continue
		}
		iter.it.Prev()
		break
	}
```
calls the baseIterator `Prev` and `Next` functions, meaning it will probably return the first version if the iterator is reversed.  

Spotted by Fred

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #22

## Description

Returns the correct value-version when iterating through the memory store in reverse.

Also documents a newly discovered badger iterator bug, and a bug in the btree implementation.

The memory store iterator has been restructured somewhat in this PR, consider reviewing the whole iter.go file as if it were new, I'm happy to bring into scope any suggestions for unchanged lines here.

### CODE REVIEW

File: test/integration/iterator/prefix_test.go [hunk 1]
```diff
@@ -31,3 +32,52 @@ func TestIteratorPrefix(t *testing.T) {
...
+		Actions: []action.Action{
+			action.Set([]byte("k"), []byte("v")),
+			action.Set([]byte("k1"), []byte("v1")),
+			&action.Iterate{
+				IterOptions: corekv.IterOptions{
+					Prefix: []byte("k"),
+				},
+				Expected: []action.KeyValue{
+					// `k` should not be yielded, but it is.
+					{Key: []byte("k"), Value: []byte("v")},
```
Comment (fredcarle) [inline test/integration/iterator/prefix_test.go:75]: question: Why is this unwanted behaviour? If it didn't return a key matching exactly the prefix, I would think it would be wrong.

Comment (AndrewSisley) [reply test/integration/iterator/prefix_test.go:75]: The existing documentation said that was undesirable, and that prefix iterators should only return values within the prefix, not a key exactly matching the prefix.

It could be that @jsimnz changed his mind after adding the documentation, and changed the badger code but not the memory store.

You can see the original documentation on (old) line 46-50 of `memory/iter.go`.

File: memory/iter.go [hunk 2]
```diff
@@ -7,210 +7,174 @@ import (
...
+	// The key at which this iterator ends, inclusive.
+	end []byte
 
-	// if the first key is an exact match to the prefix, skip next
-	// since prefix is a *strict* subset prefix
-	if pIter.curItem != nil && bytes.Equal(pIter.Key(), prefix) {
-		pIter.Next()
-	}
+	// If this is true, `start` is inclusive, else `start` is exclusive.
+	mayExactlyMatchStart bool
```
Comment (shahzadlone) [inline memory/iter.go:24]: nitpick: when `mayExactlyMatchStart` is true, `start` is for sure inclusive it seems like which is why the `may` might be confusing. Suggesting renaming to perhaps, `isStartInclusive` or `isStrictStart`.

File: memory/iter.go [hunk 3]
```diff
@@ -7,210 +7,174 @@ import (
...
 
-	return bytes.HasPrefix(item.key, prefix) && !bytes.Equal(item.key, prefix)
-}
+	iter := &iterator{
+		db:      db,
+		version: version,
+		it:      it,
+		start:   start,
+		end:     end,
+		// A prefix iterator should not return a key exactly matching itself.
```
Comment (shahzadlone) [inline memory/iter.go:53]: question: What is meant by a `prefix` iterator here?

question: Why should (should be this be a "must"?) it not return a key exactly matching itself.

File: memory/iter.go [hunk 4]
```diff
@@ -7,210 +7,174 @@ import (
...
-func (iter *dsPrefixIter) loadLatestItem() {
-	curItem := iter.it.Item()
-	for iter.it.Next() {
-		if bytes.Equal(curItem.key, iter.it.Item().key) {
-			curItem = iter.it.Item()
-			continue
-		}
-		iter.it.Prev()
-		break
+func (iter *iterator) Valid() bool {
```
Comment (shahzadlone) [inline memory/iter.go:107]: suggestion: Can you document what it means to be valid for an iterator? Or rather can makes it not valid?

File: memory/iter.go [hunk 5]
```diff
@@ -7,210 +7,174 @@ import (
...
 
-func (iter *dsRangeIter) Domain() (start []byte, end []byte) {
-	return iter.start, iter.end
-}
-
-func (iter *dsRangeIter) Valid() bool {
-	if iter.curItem == nil {
-		return false
+	if iter.it.Item().isDeleted {
+		iter.Next()
```
Comment (shahzadlone) [inline memory/iter.go:152]: question: Another `Next` call is called is the latest item in the initial `Next` call was deleted? This means that if there are many deleted items, one next call will skip all of them? Just confirming if that is the desired behavior? Is there a way for caller to control this logic (not skip and decide themselves when they want to call `Next()` next.

**Review by shahzadlone — APPROVED** [review]
LGTM

File: memory/iter.go (hunk 2 above)
Comment (AndrewSisley) [reply memory/iter.go:24]: Good shout, thanks Shahzad - will change.

- [ ] Rename `mayExactlyMatchStart`

File: memory/iter.go (hunk 3 above)
Comment (AndrewSisley) [reply memory/iter.go:53]: > What is meant by a prefix iterator here?

An iterator that covers a prefix.  I consider this to be covered by the function name, and the only place where it is called.

> must

I like this, thanks - I'll change it to `must`

- [ ] Reword should to must

File: memory/iter.go (hunk 4 above)
Comment (AndrewSisley) [reply memory/iter.go:107]: I consider that out of scope here.  This is a function that implements an interface, and the documentation should exist on that interface.

None of the production code interfaces in this repo are currently documented, but that is out of scope.  I'll add a ticket though in case that gets forgotten (I don't see that as a prerequisite for integrating into Defra, but it'll be a lot easier for me to do now while everything is fresh than it would be for me/someone-else to do in a few months time).

Comment (AndrewSisley) [reply memory/iter.go:107]: https://github.com/sourcenetwork/corekv/issues/30

File: memory/iter.go (hunk 5 above)
Comment (AndrewSisley) [reply memory/iter.go:152]: Yes.  The stores never returned deleted items, the fact that deleted items exist in an internal implementation detail of this type.

File: memory/iter.go (hunk 4 above)
Comment (AndrewSisley) [reply memory/iter.go:111]: The file was actually lacking a type check showing that this implemented the interface, I've added one in to this PR.

Comment (AndrewSisley) [reply memory/iter.go:111]: Thank you very much for flagging this Shahzad, I've found a whole bunch of issues when trying to document the public stuff!

File: test/integration/iterator/prefix_test.go (hunk 1 above)
Comment (jsimnz) [reply test/integration/iterator/prefix_test.go:75]: This is a property that comes from the original `go-datastore/query` package we use. It uses this "strict prefix" semantics, so my intent was to keep those semantics the same for the entire CoreKV prefix iterator design.

Comment (AndrewSisley) [reply test/integration/iterator/prefix_test.go:75]: Discussed in standup, the team agreed that exact matches to the prefix should be returned.  I have updated/inversed https://github.com/sourcenetwork/corekv/issues/27 and will tackle this before integrating coreKV into Defra.

File: memory/iter.go [hunk 6]
```diff
@@ -4,341 +4,250 @@ import (
...
+			if !iter.hasItem {
+				// If no items were found above or on the upper bound, we can move to the end of the
+				// BTree.
+				iter.hasItem = iter.it.Last()
+			}
+
+			if !iter.hasItem {
+				// If there are no items found at this point, it means the store is empty.
+				return
+			}
```
Comment (fredcarle) [inline memory/iter.go:217]: todo: Reverse`Seek` is a bit broken. If I have `k1, k2, k3` and I want to seek to `k2` with or without specifying a specific end, it will return `k3` but I would expect `k2`.

You basically just need to add this at the top of the if-else statement to take into account the key match.
```go
if result.key != nil {
  iter.hasItem = iter.it.Seek(dsItem{key: result.key, version: version})
} else if iter.end == nil {
  ...
```

**Review by fredcarle — CHANGES_REQUESTED** [review]
Just one bug to fix with the `Seek` method.

File: memory/iter.go (hunk 6 above)
Comment (fredcarle) [reply memory/iter.go:217]: todo: Also please add a unit test that shows it works as expected.

Comment (AndrewSisley) [reply memory/iter.go:217]: Nice find! It definitely looks like it wont work correctly, which means something needs to change, thanks Fred :)

- [ ] Reverse Seek bug?

Comment (fredcarle) [reply memory/iter.go]: There is still a small bug here. If i have `k1, k2, k3, k4` and I define the end as `k3` with `reverse = true`, The initial value will be `v2` but if I try to seek to `k4`, it will return `k3` with value `v3`. I would expect `k2` to be returned.

Comment (AndrewSisley) [reply memory/iter.go]: `End` is inclusive, so returning `k3` is correct.

Comment (AndrewSisley) [reply memory/iter.go]: Partially discussed over discord, continuing here.

`End` is only inclusive depending on how you look at `Reverse`.  Fred pointed out that `end` (implementation prop, not the option) should be exclusive if driven by a `Prefix` option, as otherwise it returns really weird results.

Badger behaviour is broken here and cannot be used for comparison https://github.com/sourcenetwork/corekv/issues/38.

I'm going to make `end`/`End` always exclusive for now, as skipping `End` is less weird than including `end` in a reversed `Prefix` iterator.  We can discuss the medium/long-term plan in a documentation-PR that I plan on opening soon (I plan on discussing a few more items there too).

- [ ] Make `end` exclusive

**Review by fredcarle — APPROVED** [review]
LGTM. Thanks for the changes.
