### PR TITLE
fix: Limit badger iterator seek to iterator bounds

### LINKED ISSUE #19: Badger panics when iterating past the end of an iterator
This is documented by the following tests:

- `TestIteratorReverseNextValid_Badger`

### LINKED ISSUE #38: Badger allows seeking beyond end of the iterator
This is documented by `TestIteratorReverseEndSeekValidValue_Badger` and `TestIteratorStartSeekValidValue_Badger`.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #38
Resolves #19

## Description

Limit badger iterator seek to iterator bounds.

Also fixes a panic when calling badger.Next, and simplifies the badger iterator code.

### CODE REVIEW

File: badger/iter.go [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+}
+
+func (it *iterator) Next() (bool, error) {
+	if it.reset {
+		return it.restart()
+	}
+
+	if !it.i.Valid() {
+		// `it.i.Next()` will panic if we attempt to call it having already reached
+		// the iterator end, so we much return before trying to make that call if we can.
```
Comment (nasdf) [inline badger/iter.go:99]: typo: `much` -> `must`

**Review by nasdf — APPROVED** [review]
LGTM

**Review by shahzadlone — APPROVED** [review]
Cheers

File: badger/iter.go (hunk 1 above)
Comment (AndrewSisley) [reply badger/iter.go:99]: :) I am introducing way too many typos atm, thanks Keenan

- [ ] Fix typo
