### PR TITLE
fix: Return error when iterating through closed store

### LINKED ISSUE #67: Badger iterator panics if store is closed
Is quite annoying as background routines panic quite a lot due to this when closing the store in tests.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #67

## Description

Returns an error when iterating through closed store instead of panicing.

This was particularly annoying in Defra, as background routines would often panic in test teardown, making them fairly flaky.

### CODE REVIEW

File: badger/badger.go [hunk 1]
```diff
@@ -78,21 +85,29 @@ func (b *Datastore) Delete(ctx context.Context, key []byte) error {
...
 func (b *Datastore) Close() error {
+	b.closeLk.Lock()
+	defer b.closeLk.Unlock()
+	b.closed = true
+
 	return b.db.Close()
 }
 
-func (b *Datastore) Iterator(ctx context.Context, iterOpts corekv.IterOptions) corekv.Iterator {
+func (b *Datastore) Iterator(ctx context.Context, iterOpts corekv.IterOptions) (corekv.Iterator, error) {
```
Comment (fredcarle) [inline badger/badger.go:95]: nitpick: We have a mix of `b` and `d` receivers for the same struct. `b` seems weird as there is not even a `b` in `Datastore`.  `d` seems a lot more appropriate.

Comment (AndrewSisley) [reply badger/badger.go:95]: The type name used to be `badgerStore` or something similar, the receiver names never got updated when I changed the type name.  I'm not terribly fussed about it given the tiny scope of these functions, and the fact that a lot of reciever and type names are still a little off in this repo (e.g. `bTxn`, slightly further down in this file) - could maybe sort them all out in another PR if/when prioritised.

File: test/multiplier/txn.go
Comment (fredcarle) [inline test/multiplier/txn.go:1]: thought: The `Apply` methods are a bit hard to follow. It would be helpful to add a description of what each loop is trying to accomplish.

**Review by fredcarle — APPROVED** [review]
LGTM

File: test/multiplier/txn.go
Comment (AndrewSisley) [reply test/multiplier/txn.go:1]: I agree that they are not great, but do not think a comment would be sufficient - the loops themselves are kind of hard to describe.  I've created https://github.com/sourcenetwork/corekv/issues/72 to deal with it properly.
