### PR TITLE
fix: Return exact prefix match from memory iterator

### LINKED ISSUE #27: Memory prefix iterator does not return self
If given prefix `K`, the store will not return the key `K`. Badger store works correctly, although this looks accidental as there appears to be code that tries to prevent the return of that key.

This is documented by test `TestIteratorPrefix_DoesNotReturnSelf_Badger`/`TestIteratorPrefix_DoesNotReturnSelf_Memory`.

Make sure the documentation in `IterOptions` is updated when you do this.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #27

## Description

Returns exact prefix match from memory iterator, matching the badger behaviour.

Also removes some dead code I accidentally left in from a previous PR.

### CODE REVIEW

File: memory/iter.go [hunk 1]
```diff
@@ -22,9 +22,6 @@ type iterator struct {
 	// The key at which this iterator ends, inclusive.
 	end []byte
 
-	// If this is true, `start` is inclusive, else `start` is exclusive.
-	isStartInclusive bool
```
Comment (AndrewSisley) [inline memory/iter.go:26]: @fredcarle Sorry as I pushed back on doing this in an earlier PR as I thought this would be more involved than this and require cleanup in badger, however the badger code that I thought was trying to do this was trying to do something else instead and this change was fairly easy.

**Review by shahzadlone — APPROVED** [review]
LGTM
