### PR TITLE
fix: Handle namespace iterator if no prefix/start/end

### LINKED ISSUE #60: Namespace iterator escapes namespace
Given an empty string as a prefix, the namespace iterator appears to escape the namespace and starts returning stuff from outside the boundary.

Keys in store:
```
/db/system/seq/collection
/db/system/init
/db/system/seq/collection
/db/system/seq/field/1
/db/system/seq/field/1
/db/system/schema/version/v/bafkreia3o3cetvcnnxyu5spucimoos77ifungfmacxdkva4zah2is3aooe
/db/system/collection/id/1
/db/system/collection/name/Users
/db/system/collection/version/bafkreia3o3cetvcnnxyu5spucimoos77ifungfmacxdkva4zah2is3aooe/1
/db/system/collection/root/1/1
/db/blocks/CIQNAJMNOAIG77CMPPXQTGT3SZA6KTTVBTVPOXBKIOSTCVXXJPGSTMQ
/db/data/�/v/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1
/db/data/�/p/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1/bafyreigqewgxaedp7rghx3yjtj5zmqpfjz2qz2xxlqvehjjrk33uxtjjwi
/db/blocks/CIQD6AKUH2OI6XZ3MHHNM6ARZXWCO2CHW7F2ZVDLWYBEFGGB6D4YZOI
/db/data/�/v/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/v
/db/data/1/pk/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/C/bafyreib7afkd5hepl45wdtwwpai433bhnbd3ps5m2rv3masctda7b6mmxe
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/C/bafyreib7afkd5hepl45wdtwwpai433bhnbd3ps5m2rv3masctda7b6mmxe
/db/blocks/CIQBO6CDRZ5VJJZN7WI4ZRJ6KDOWR6UEJV6NKYWNE73IVBZZ5DL4ZIY
/db/data/�/v/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1
/db/data/�/p/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/1/bafyreiaxpbby462uu4w73eomyu7fbxli7kce27gvmlgsp5ukq446rv6mum
/db/blocks/CIQOEQBIG2DWDHDMWY52FVN4XR4P76JYKZAEMHSCQRCBRBRRJLQG3SA
/db/data/�/v/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/v
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/C/bafyreihciaudnb3btrwlmo5c2w6ly6h77e4fmqcgdzbiirayqyyuvydnza
/db/heads/d/bae-6845cfdf-cb0f-56a3-be3a-b5a67be5fbdc/C/bafyreihciaudnb3btrwlmo5c2w6ly6h77e4fmqcgdzbiirayqyyuvydnza
```
Namespace:
```
/db/heads
```
Prefix:
```
""
(from):
hf.kvIter = txn.Headstore().Iterator(ctx, corekv.IterOptions{
	Prefix: prefixBytes,
})
```
Last key yielded (before error/panic):
```
s/CIQBO6CDRZ5VJJZN7WI4ZRJ6KDOWR6UEJV6NKYWNE73IVBZZ5DL4ZIY
```
Looks like it chopped off `/db/block` from in front of `/db/blocks/CIQBO6CDRZ5VJJZN7WI4ZRJ6KDOWR6UEJV6NKYWNE73IVBZZ5DL4ZIY`.

Make sure the test gap is closed.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #60

## Description

Handles namespace iterator if no prefix/start/end provided.

Includes a lazy workaround for a known bug in the tidwall/btree implementation that was hit when fixing #60.  Performance deemed to be low enough priority in the memory store iterator constructor at the moment to tolerate a simple workaround.

### CODE REVIEW

File: memory/iter.go [hunk 1]
```diff
@@ -28,19 +28,45 @@ type iterator struct {
...
 	// returned to the beginning on the next [Next] call.
 	reset bool
+
+	// These properties are used by a work around for a bug in the btree implementation:
+	// https://github.com/tidwall/btree/issues/46 - these properties and the work around
+	// should be removed when the btree bug is fixed.
+	//
+	// `TestBTreePrevBug` also documents this issue.
+	lastItem  dsItem
+	firstItem dsItem
```
Comment (fredcarle) [inline memory/iter.go:38]: todo: Please add a documentation that this is only needed for `reverse` operations.

**Review by fredcarle — APPROVED** [review]
LGTM. Just one minor todo before merge.

File: memory/iter.go (hunk 1 above)
Comment (AndrewSisley) [reply memory/iter.go:38]: Will do.

- [ ] Note is for reverse only
